//! Parses the canonical artifact once, at build time, into static Rust arrays.
//!
//! This runs on the host during compilation — never inside the zkVM guest. The
//! guest gets plain array data with no JSON/float parsing at proof time, which is
//! what actually costs cycles in a soft-float RV32IM zkVM.
//!
//! Float literals are emitted with Rust's `{:?}` formatting, which round-trips
//! exactly back to the same `f64` bit pattern the build-time `serde_json` parse
//! produced — so this is not a re-derivation of the model, just a relocation of
//! where parsing happens. `model_hash()` still hashes `ARTIFACT_BYTES` (the exact
//! file bytes), which this script never touches.
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct Tree {
    children_left: Vec<i32>,
    children_right: Vec<i32>,
    feature: Vec<i32>,
    threshold: Vec<f64>,
    leaf_values: Vec<Vec<f64>>,
}

#[derive(serde::Deserialize)]
struct Forest {
    n_classes: usize,
    n_estimators: usize,
    trees: Vec<Tree>,
}

#[derive(serde::Deserialize)]
struct Artifact {
    forest: Forest,
    /// Positions in the 44-dim transformed feature space the student consumes.
    /// Its length is the guest's input vector dimension.
    selected_feature_indices: Vec<i64>,
}

fn main() {
    const ARTIFACT_PATH: &str = "risc0_distilled_model.json";
    println!("cargo:rerun-if-changed={ARTIFACT_PATH}");

    let bytes = fs::read(ARTIFACT_PATH).expect("read canonical artifact");
    let artifact: Artifact = serde_json::from_slice(&bytes).expect("parse canonical artifact");
    let n_classes = artifact.forest.n_classes;
    let n_estimators = artifact.forest.n_estimators;
    let input_dim = artifact.selected_feature_indices.len();
    assert_eq!(artifact.forest.trees.len(), n_estimators, "tree count mismatch");
    // The selected vector's length must cover every feature the forest routes on.
    let max_feature = artifact
        .forest
        .trees
        .iter()
        .flat_map(|t| t.feature.iter())
        .copied()
        .max()
        .unwrap_or(-1);
    assert!(
        (max_feature as usize) < input_dim,
        "forest routes on feature {max_feature} but input_dim is only {input_dim}"
    );

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from {ARTIFACT_PATH} — do not edit by hand.").unwrap();
    writeln!(out, "pub const N_CLASSES: usize = {n_classes};").unwrap();
    writeln!(out, "pub const N_ESTIMATORS: usize = {n_estimators};").unwrap();
    writeln!(out, "/// Length of the selected transformed feature vector the guest consumes.").unwrap();
    writeln!(out, "pub const INPUT_DIM: usize = {input_dim};").unwrap();
    writeln!(out, "pub struct TreeData {{").unwrap();
    writeln!(out, "    pub children_left: &'static [i32],").unwrap();
    writeln!(out, "    pub children_right: &'static [i32],").unwrap();
    writeln!(out, "    pub feature: &'static [i32],").unwrap();
    writeln!(out, "    pub threshold: &'static [f64],").unwrap();
    writeln!(out, "    pub leaf_values: &'static [[f64; N_CLASSES]],").unwrap();
    writeln!(out, "}}").unwrap();

    writeln!(out, "pub static TREES: [TreeData; N_ESTIMATORS] = [").unwrap();
    for tree in &artifact.forest.trees {
        let n = tree.children_left.len();
        assert_eq!(tree.children_right.len(), n);
        assert_eq!(tree.feature.len(), n);
        assert_eq!(tree.threshold.len(), n);
        assert_eq!(tree.leaf_values.len(), n);

        writeln!(out, "  TreeData {{").unwrap();
        write_i32_slice(&mut out, "children_left", &tree.children_left);
        write_i32_slice(&mut out, "children_right", &tree.children_right);
        write_i32_slice(&mut out, "feature", &tree.feature);
        write_f64_slice(&mut out, "threshold", &tree.threshold);

        write!(out, "    leaf_values: &[").unwrap();
        for row in &tree.leaf_values {
            assert_eq!(row.len(), n_classes, "leaf row length != n_classes");
            write!(out, "[").unwrap();
            for v in row {
                assert!(v.is_finite(), "non-finite leaf value in canonical artifact");
                write!(out, "{v:?},").unwrap();
            }
            write!(out, "],").unwrap();
        }
        writeln!(out, "],").unwrap();
        writeln!(out, "  }},").unwrap();
    }
    writeln!(out, "];").unwrap();

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("forest_data.rs"), out).unwrap();
}

fn write_i32_slice(out: &mut String, name: &str, values: &[i32]) {
    write!(out, "    {name}: &[").unwrap();
    for v in values {
        write!(out, "{v},").unwrap();
    }
    writeln!(out, "],").unwrap();
}

fn write_f64_slice(out: &mut String, name: &str, values: &[f64]) {
    write!(out, "    {name}: &[").unwrap();
    for v in values {
        assert!(v.is_finite(), "non-finite threshold in canonical artifact");
        write!(out, "{v:?},").unwrap();
    }
    writeln!(out, "],").unwrap();
}
