"""Shared fixtures for the API route tests.

Several route tests call ``load_artifacts("model_store")``, which needs trained
model artifacts (``full.joblib`` etc.) on disk. Those artifacts are gitignored
(generated by ``ml.models.train``), so a fresh checkout / CI runner has none.

This session-scoped, autouse fixture trains a small synthetic model into
``model_store`` exactly once *if* one is not already present — making the suite
self-contained without a separate CI training step, and leaving any real trained
model in place untouched.
"""

from __future__ import annotations

import csv
from pathlib import Path

import pytest

from ml.features.population_v1 import POPULATION_FEATURE_NAMES
from ml.models.registry import model_paths
from ml.models.train import train


@pytest.fixture(scope="session", autouse=True)
def _ensure_trained_model() -> None:
    paths = model_paths("model_store")
    if paths["full"].exists():
        return  # real (or previously-trained) artifacts already present.

    paths["base"].mkdir(parents=True, exist_ok=True)
    population_csv = paths["base"] / "_test_population.csv"
    with population_csv.open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["account_id", *POPULATION_FEATURE_NAMES])
        for row_id in range(40):
            row: list[object] = [f"G{row_id:04d}"]
            for col_idx, name in enumerate(POPULATION_FEATURE_NAMES):
                value = float((row_id + 1) * (col_idx + 2))
                if name == "failed_ratio":
                    value = min((row_id % 5) / 10.0, 1.0)
                elif name == "native_send_ratio":
                    value = 1.0 if row_id % 3 else 0.5
                row.append(value)
            writer.writerow(row)

    train(
        "model_store",
        population_csv=population_csv,
        processed_csv=Path("model_store") / "_test_processed.csv",
        build_zk=False,
    )
