"""baseline schema (accounts, operations, attestations)

Revision ID: 9a86bb72579f
Revises: 
Create Date: 2026-07-07 02:41:26.752215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a86bb72579f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('stellar_address', sa.String(length=56), nullable=False),
    sa.Column('sequence', sa.String(length=32), nullable=True),
    sa.Column('subentry_count', sa.Integer(), nullable=True),
    sa.Column('last_modified_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('stellar_address')
    )
    op.create_table('attestations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stellar_address', sa.String(length=56), nullable=False),
    sa.Column('risk_bucket', sa.Integer(), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('full_model_hash', sa.String(length=64), nullable=False),
    sa.Column('distilled_model_hash', sa.String(length=64), nullable=False),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('zk_verified', sa.Boolean(), nullable=False),
    sa.Column('tx_hash', sa.String(length=64), nullable=False),
    sa.Column('attestor', sa.String(length=56), nullable=False),
    sa.Column('issued_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('submission_mode', sa.String(length=32), nullable=False),
    sa.Column('submission_detail', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attestations_created_at'), 'attestations', ['created_at'], unique=False)
    op.create_index(op.f('ix_attestations_stellar_address'), 'attestations', ['stellar_address'], unique=False)
    op.create_table('operations',
    sa.Column('op_id', sa.String(length=32), nullable=False),
    sa.Column('stellar_address', sa.String(length=56), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('type_i', sa.Integer(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('op_id')
    )
    op.create_index(op.f('ix_operations_created_at'), 'operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_operations_stellar_address'), 'operations', ['stellar_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_stellar_address'), table_name='operations')
    op.drop_index(op.f('ix_operations_created_at'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_attestations_stellar_address'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_created_at'), table_name='attestations')
    op.drop_table('attestations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
